### ISSUE TITLE
Invalid Login

### ISSUE THREAD

**Issue by glberen** [KaiserSoft/PIA-Tunnel#10]
Hi,

Just updated and now I'm getting an Invalid Login error on the drop-down menus for the pia connect points and the daemon settings. It also won't connect now. 

The VPN Accounts setup page is blank. I have rebooted. 

Any ideas on what should be done next besides wiping and starting over, which I'd rather not do? 

Thanks!

**Comment by glberen** [comment]
Thanks. Back up and running again. The pia-start script is looking for /pia/ovpn/pia, which doesn't exist. I symlinked pia to PIAtcp and got the command-line to list out the endpoints, but it still wouldn't connect.

**Comment by KaiserSoft** [comment]
Sorry guys. Your messages came in when I was already in bed.

The path /pia/ovpn/pia is wrong. I will correct this ASAP

--
Mirko

**Comment by KaiserSoft** [comment]
I checked the ovpn files and they appear to be correct. I can reproduce the issue by only enabling "PIAudp", then applying the update. Are all of you using the UDP version?

I removed UDP because the connection was using the old certificates. These old certificates may have been compromised by Russian authorities. IF they seized the Russian servers without notice.
https://www.privateinternetaccess.com/forum/discussion/21779/we-are-removing-our-russian-presence

I highly recommend that you don't use the old release anymore and enable PIAtcp for now. I will try to get the settings for UDP from the PIA desktop software later today.

Please use PIAtcp for now.

**Comment by glberen** [comment]
So, in general settings, I switched over to PIAtcp and rebooted the VM, but it's still connecting via UDP. The Pia Daemon settings all show UDP connections in the drop downs. I haven't pressed the update button yet because of this. Trying to figure out how the daemon settings are populated right now, so I can load PIAtcp connections before running the update in case that causes a problem as well.

**Comment by glberen** [comment]
Well, I went ahead and reset to master and pulled everything down. I got a bunch of new VPN providers, but I'm getting 'invalid login data' on all the dropdowns for the endpoints, which is where I was at the beginning. Something with the previously running UDP is screwing it up.

**Comment by glberen** [comment]
And...things ended up so hosed, nothing would work. I ended up restoring a backup of the VM. Now, the question is how to completely disable UDP? Clicking it off in the settings and then choosing PIAtcp doesn't change the connection settings for me at all. What next besides just building another one?

**Comment by KaiserSoft** [comment]
Don't do that. Master is the development branch and not compatible to the current stable release. It also contains a bug when you attempt to switch VPN providers.

You need to redeploy the VM at this point.

Work was quite busy today so I did not have time to get UDP working. Will look into it tomorrow.
PIAtcp will work with a fresh VM.

--
Mirko

**Comment by KaiserSoft** [comment]
BTW, you broke the online update if you went back to a previous release.

You need to checkout "release_php-gui" to get back to current versionn but NOT if you already checked out master. Master is not compatible to the current stable version at all and will screw everything up.

--
Mirko

**Comment by glberen** [comment]
Yep, I sure did break it. No big deal. I think I'll just deploy another VM when I get a chance and start out fresh...maybe with the V2 one you're working on. The backup VM is working. I just won't update it till I get a new one built.

**Comment by glberen** [comment]
All good now. I saw your update about logging out to repopulate the connection endpoints and that worked. Updated the backup vm and all up to spec now. Thanks!

**Comment by bjay1404** [comment]
I'm on the commit from July 12th, didn't see the udp connections get added
back.  Did those get added back? This project is fantastic!

**Comment by glberen** [comment]
No, only TCP in there right now. I just switched to that for the time being.

**Comment by KaiserSoft** [comment]
Sorry about the issue guys. 
PIA-Tunnel v2 adds fixes for updating the cached values when you store settings. So something like this should not happen again.

I'll post on the rss feed as soon as I have another update
http://www.kaisersoft.net/pia_latest.xml

**Comment by glberen** [comment]
No worries! Thank you so much for putting all this together.

**Comment by bjay1404** [comment]
Yeah no worries at all, incredible software.

**Comment by bjay1404** [comment]
So how we do update to version 2?

**Comment by KaiserSoft** [comment]
Looks like I found the correct settings for the new UDP settings. I'll run a few more test before I prepare the update.


> So how we do update to version 2?

I will post instructions on the rss feed once release-v2 is ready. You'll need to download a Debian 8 based VM or you can use a provided setup script to install release-v2 onto your own Debian 8 based installation.

**Comment by KaiserSoft** [comment]
I just pushed an update which adds PIAudp back in.
If you went back to a previous release you should run the following commands

> git checkout release_php-gui
> git reset --hard
> pia-update

You should now see "PIAudp" in the list of VPN providers again. Select it and logout to refresh the list of VPN connections. Everything should work again afterwards.

Please let me know if you run into any issues.

**Comment by EricTheRed1** [comment]
I need some help.  I did a full reset and updated to the latest version.  It connects for about a minute and then disconnects.  i've tried with PIA TCP and TCP High.  No luck

**Comment by KaiserSoft** [comment]
> I need some help. I did a full reset and updated to the latest version. It connects for about a minute and then disconnects. i've tried with PIA TCP and TCP High. No luck

Is this a new installation or did this happen after the upgrade. Please open a separate bug report if this is not related to the latest update.
You can find the logs in /pia/cache and monitor what is going on with the following command

> tail -f /pia/cache/session.log
