### ISSUE TITLE
how to add vpn server ?

### ISSUE THREAD

**Issue by adrianmak** [KaiserSoft/PIA-Tunnel#6]
i found that some new vpn servers from privateinternetaccess.com are missing. For example, japanese, hong kong connections

how to add these two vpn connection ?

**Comment by KaiserSoft** [comment]
Thanks for letting me know. I believe some are new so they are not on the list yet.
I plan on pushing an update out today that will add the missing servers.

**Comment by KaiserSoft** [comment]
I have added the new servers and everything looks good so far. I'll test the changes over night and push the release out tomorrow.

Please logout after you receive the update because the list of servers is cached.

**Comment by KaiserSoft** [comment]
OK update is out. You may reboot the VM to force an update check.
Please remember to logout of the WebUI or the new VPN endpoints will not show up.
